name: flutter_jalali_date_picker
description: "A Jalali/Persian Date Time Picker with Format Date to Persian"
version: 2.0.0
homepage: "https://github.com/ARASHz4/flutter_jalali_date_picker"

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:

